language: python
python:
  - "3.7"
  - "3.8"

install:
- pip install pytest-cov
- pip install pytest-pylint
  
script:
- pytest --pylint --cov-report term-missing --cov=tests/

after_success:
- bash <(curl -s https://codecov.io/bash)
